### PR TITLE
Fixes bug in line source calculation

### PR DESCRIPTION
**Pull request by joseph-tharayil**
Hi all,
I believe that I have found a bug in the calculation of the line-source approximation. The value r2 should be the difference between l2 and the distance from the electrode to the start of the segment, not the difference between h2 and the electrode-segment distance.

### CODE REVIEW

**Comment by espenhgn** [comment]
Hmm, wouldn't this imply some issue with the formalism as detailed in Gary Holt's thesis from 1998?
image

@torbjone, can you look into this?

**Comment by joseph-tharayil** [comment]
@espenhgn yes, I believe that the same typo is in equation C.15. If point (x1,y1,z1) is the left end of the segment in Figure C.2, then clearly it should be l**2 in C.15. If (x1,y1,z1) is the right end of the segment, then C.15 is correct, but C.14 would produce an incorrect value for h

**Comment by torbjone** [comment]
Hi all,
I don't think I have noticed before, but I agree that there seems to be a typo in C.15 in the paper. Instead of x_1, y_1, z_1 it should be x_2, y_2, z_2. However, in LFPy it is implemented like this,
r2 = _r2_calc(xend, yend, zend, x, y, z, h)
and xend, yend, zend correspond to  x_2, y_2, z_2 so I think this is actually correct.

I also tested the two versions, and the original version gave this result, which looks correct to me:
orig_test_root_as_point
The modified version gave this result, where it looks like something is wrong:
mod_test_root_as_point

So as far as I can tell, the original implementation is correct. Please let me know if I have missed something though!

Best,
Torbjørn

**Comment by espenhgn** [comment]
Perhaps good to compare with other implementations e.g., in [bmtk](https://github.com/AllenInstitute/bmtk/blob/e57c84cec56fc0a7fb5e9c5f3c43067dc9d8eba7/bmtk/simulator/bionet/modules/ecp.py#L243), which may be more closely based on the original codes from Holt or via the later [Gold et al.](https://pubmed.ncbi.nlm.nih.gov/16467426/) paper(s).

**Comment by joseph-tharayil** [comment]
Sorry for the delayed response. You are correct; I misunderstood how the LFPy implementation worked

**Pull request closed without merging**
