### PR TITLE
Fix 149 mod

### PR DESCRIPTION
**Pull request by torbjone**
I suggest to move away from testing "foo == 0" because of roundoff errors

### CODE REVIEW

**Comment by espenhgn** [comment]
Does this fix actually fix any problems that you saw? I feel like setting some explicit but arbitrary small threshold value `1E-9` could result in new issues. 
@solveignaess, do you happen to know?

**Comment by espenhgn** [comment]
Btw., `autopep8 --in-place --aggressive --aggressive eegmegcalc.py` would likely fix the failing flake8 tests.

**Comment by espenhgn** [comment]
Well, in this case I think we should have `if np.linalg.norm(...) > 0:` in each case (`p, p_tan, p_rad`), which imply that we compute the corresponding potential contribution for dipole components no matter how small as long as they are not zero.
For the `self._theta` checks it looks like they should be left as is, as both `np.arccos(-1) == np.pi` and `np.arccos(1) == 0` evaluates to True. The function returns numeric values for input on the interval [-1, 1] and NaNs otherwise. In `_calc_theta` NaNs are replaced by zeros. 

Anyway, do you have example coordinates for `p` and `r_electrode` where RuntimeWarnings or similar are triggered? So far I didn't see any. Presumably this occur when the denominator `np.outer(np.linalg.norm(rxy, axis=1), np.linalg.norm(x, axis=1))` returns zeros?

**Comment by torbjone** [comment]
You are probably right, that looks like a better solution,
Here is an example that causes a RuntimeWarning locally, presumably because p_tan is very close to, but not exactly, zero:

import numpy as np
from lfpykit.eegmegcalc import FourSphereVolumeConductor

radii_4s = [110000., 9000000., 9500000., 10000000.]  # (µm)
sigmas_4s = [0.3, 0.3, 0.3, 0.3]  # (S/m)
cdm_mag = 1e6

dipole_location = [-100000 / np.sqrt(2), 0, -100000 / np.sqrt(2)]

p = np.array([[+cdm_mag], [0], [+cdm_mag]])

elecs_x_4s =  np.array([101000])
elecs_y_4s = np.array([0])
elecs_z_4s = np.array([0])

r_elecs_4s = np.vstack((elecs_x_4s, elecs_y_4s, elecs_z_4s)).T
sphere_model = FourSphereVolumeConductor(r_elecs_4s, radii_4s, sigmas_4s)
eeg_4s = sphere_model.get_dipole_potential(p, np.array(dipole_location))

**Comment by espenhgn** [comment]
Thanks, can reproduce this zero-zero division issue. But hey is that function `_calc_phi` confusing.

**Pull request closed without merging**
